trigger:
  branches:
    include:
      # trigger for merge queue branches
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipAzureAuth: true
    validationJobs:
      - name: Check Commits
        steps:
          - template: ../steps/node_script.yml
            parameters:
              # only run commitlint on branches, not main
              condition: ne(variables['Build.SourceBranchName'], 'main')
              nodeVersion: 22
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              # only run commitlint on branches, not main
              condition: ne(variables['Build.SourceBranchName'], 'main')
              nodeVersion: 22
              script: npm run commitlint
